### ISSUE TITLE
Fails to build with gtest 1.13 (requires C++14)

### ISSUE THREAD

**Issue by sebastic** [eclipse/sumo#13484]
As reported in [Debian Bug #1038897](https://bugs.debian.org/1038897):
> Your package FTBFS with googletest 1.13 in unstable:
> ```
>  In file included from /usr/include/gtest/gtest-message.h:57,
>                   from /usr/include/gtest/gtest-assertion-result.h:46,
>                   from /usr/include/gtest/gtest.h:64,
>                   from /<<PKGBUILDDIR>>/unittest/src/netbuild/NBHeightMapperTest.cpp:23:
>  /usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
>    270 | #error C++ versions less than C++14 are not supported.
>        |  ^~~~~
> ```
> See also: https://lists.debian.org/debian-devel/2023/06/msg00262.html

This patch has been added to the package to resolve this issue:
```diff
Description: Use C++14 for gtest 1.13.
Author: Bas Couwenberg <sebastic@debian.org>
Bug-Debian: https://bugs.debian.org/1038897

--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -94,7 +94,7 @@ if (GNU_COMPILER OR CLANG_COMPILER)
         set(CMAKE_BUILD_TYPE "Release")
     else ()
         #flags for clang and gcc in linux
-        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -pthread -Wall -pedantic -Wextra")
+        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -pthread -Wall -pedantic -Wextra")
     endif ()
     if (PROFILING)
         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pg")
```

**SUMO-version:** 1.15.0

**Operating System:** Debian GNU/Linux unstable

**Comment by sebastic** [comment]
Looks like this was fixed with https://github.com/eclipse/sumo/commit/ffeaee0a6cf3ff4f92ff03e866e684cd07b2b696
