### ISSUE TITLE
recheck building without proj

### ISSUE THREAD

**Issue by behrisch** [eclipse/sumo#4651]
> When I try to build on Ubuntu 16.04 using
> 
>     git clone --recursive https://github.com/DLR-TS/sumo.git
>     cd sumo
>     make -f Makefile.cvs
>     ./configure --with-python --without-ffmpeg
>     make -j8
> 
> I encounter the following error, which comes from
> /sumo/src/utils/geom/GeoConvHelper.cpp
> 
>     GeoConvHelper.cpp: In member function ‘const string
>     GeoConvHelper::getProjStringExpaneded() const’:
>     GeoConvHelper.cpp:435:9: error: ‘myProjection’ was not declared in
>     this scope
>          if (myProjection == 0) {
>              ^
>     GeoConvHelper.cpp:438:42: error: ‘pj_get_def’ was not declared in
>     this scope
>              return pj_get_def(myProjection, 0);
>                                               ^
>     Makefile:411: recipe for target 'GeoConvHelper.o' failed
