### ISSUE TITLE
gtfs2pt.py doesn't work in SUMO 1.14.1

### ISSUE THREAD

**Issue by DrRembo** [eclipse/sumo#11556]
Dear SUMO Team,

after upgrading SUMO from 1.13.0 to 1.14.1 the gtfs2pt.py script runs into an error:

~/GTFS_TEST/20220418$ /usr/share/sumo/tools/import/gtfs/gtfs2pt.py -n osm.net.xml --gtfs google_transit.zip --date 20220418
function import_gtfs called at Thu, 08 Sep 2022 10:59:54 +0000
function import_gtfs finished after 9.028326 seconds
Traceback (most recent call last):
  File "/usr/share/sumo/tools/import/gtfs/gtfs2pt.py", line 444, in <module>
    main(get_options())
  File "/usr/share/sumo/tools/import/gtfs/gtfs2pt.py", line 407, in main
    gtfs2fcd.main(options)
  File "/usr/share/sumo/tools/import/gtfs/gtfs2fcd.py", line 107, in main
    sumolib.writeXMLHeader(fcdFile[mode], "gtfs2fcd.py", options=options)
TypeError: writeHeader() got an unexpected keyword argument 'options'

best regards,

Emanuel

**Comment by namdre** [comment]
this looks like a version mismatch on your machine.  gtfs2pt.py loads the sumolib function based on your SUMO_HOME environment variable. If this still points to 1.13.0 then it causes the method writeXMLHeader to fail.

To debug this on your machine, add the line
`print("SUMOLIB_PATH:",sumolib.__file__)` after the `import sumolib` statement in `gtfs2pt.py`

**Comment by DrRembo** [comment]
Thank you for the hint :)
```bash
pip3 install sumolib --upgrade 
```
solved the problem
